server:
  port: 8060

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh                   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8011          #匹配后提供服务的路由地址
          uri: lb://payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/getById/**            # 断言，路径相匹配的进行路由

        - id: payment_routh2                  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8011          #匹配后提供服务的路由地址
          uri: lb://payment-service             #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/myLb/**             # 断言，路径相匹配的进行路由
            - After=2020-04-08T15:12:52.766+08:00[Asia/Shanghai]
            - Cookie=username,liang

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    instance-id: cloud-gateway
    prefer-ip-address: true