server:
  port: 8020

spring:
  application:
    name: order-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    instance-id: order-service
    prefer-ip-address: true

# feign超时控制
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
# feign日志
logging:
  level:
    com.liang.service.*: debug
