-- auto Generated on 2020-03-20
-- DROP TABLE IF EXISTS payment;
CREATE TABLE payment(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '主键id',
	serial VARCHAR (50) NOT NULL DEFAULT '' COMMENT '订单号',
	gmt_create DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '创建时间',
	gmt_modified DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '修改时间',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'payment';
