spring:
  application:
    name: sca-account-provider
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.liang.service
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  cloud:
    # 设置订阅的应用列表，默认为 * 订阅所有应用。这里，设置为 '' 表示空，不订阅任何的应用。
    subscribed-services: ""

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  service:
    vgroup-mapping:
      sca_group: default

logging:
  level:
    io:
      seata: info
    com.liang.mapper: debug

mybatis:
  mapperLocations: classpath:mapper/*.xml