server:
  port: 2005

dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  consumer:
    check: false
  cloud:
    subscribed-services: sca-account-provider,sca-storage-provider
  protocol:
    port: -1

spring:
  application:
    name: sca-consumer
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: sca-group
  service:
    vgroup-mapping:
      sca-group: sca
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.11.201:8880

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml



